version: '2'
services:

  sth:
    image: powerbr/fiware-sth-comet
    restart: always
    networks:
      default:
        aliases:
          - comet
          - history
    ports:
      - 8666:8666
    environment:
      STH_HOST: "0.0.0.0"
      DB_URI: "10.4.1.49:27017"

  # mongodb:
  #   image: "ppc64le/mongodb:2.6.10"
  #   restart: always

  mqtt:
    image: powerbr/mosquitto:1.0
    restart: always
    ports:
      - "1883:1883"

  iotagent:
    image: powerbr/iotagent-json:1.0
    restart: always
    depends_on:
      - mqtt
    volumes:
      - ./iotagent/config.js:/opt/iotajson/config.js:Z
    ports:
      - "4041:4041"
      - "8080:8080"
    extra_hosts:
      - "mongodb:10.4.1.49"
      - "orion:10.4.1.49"
    networks:
      default:
        aliases:
          - idas

  # coap:
  #   image: "powerbr/lightweightm2m-iotagent"
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - "127.0.0.1:4041:4041"
  #     - 5684:5684/udp

  # gui:
  #   image: powerbr/gui
  #   restart: always
  #   ports:
  #     - "80:80"

  # orion:
  #   image: powerbr/orion:latest
  #   restart: always
  #   ports:
  #     - "1026:1026"
  #   extra_hosts:
  #     - "mongodb:10.4.1.49"
  #   command: -dbhost mongodb

  device-manager:
    image: powerbr/device-manager:latest
    restart: always
    ports:
      - "5000:5000"
    extra_hosts:
      - "mongodb:10.4.1.49"
      - "orion:10.4.1.49"
    networks:
      default:
        aliases:
          - devm

  # auth:
  #   image: powerbr/auth
  #   restart: always
  #   depends_on:
  #     - mongodb
  #     - apigw
  #   environment:
  #     DB_HOST: "postgres"
  #     DB_USER: "postgres"
  #     DB_PWD: ""
  #     KONG_URL: "http://apigw:8001"

  # postgres:
  #   image: "ppc64le/postgres:9.4"
  #   restart: always

  # apigw:
  #   image: "powerbr/pepkong"
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8000:8000"
  #     - "8443:8443"
  #     - "127.0.0.1:8001:8001"
  #   environment:
  #     KONG_DATABASE: "postgres"
  #     KONG_PG_HOST: "postgres"
  #     KONG_LUA_CODE_CACHE: "true"
  #   networks:
  #     default:
  #       aliases:
  #         - kong

  # pdp-ws:
  #   image: powerbr/pdp-ws
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "9763:9763"
  #   volumes:
  #     - ./pdpws/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:Z

  perseo-core:
    image: powerbr/perseo-core
    restart: always
    command: -perseo_fe_url perseo-fe:9090

  perseo-fe:
    image: powerbr/perseo-fe
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - perseo-core
    extra_hosts:
      - "orion:10.4.1.49"
    environment:
      - PERSEO_MONGO_HOST=10.4.1.49
      - PERSEO_CORE_URL=http://perseo-core:8080
      - PERSEO_ORION_URL=http://orion:1026/NGSI10/updateContext

  mashup:
    image: powerbr/mashup
    restart: always
    extra_hosts:
      - "mongodb:10.4.1.49"
      - "orion:10.4.1.49"
    ports:
      - "3000:3000"
      - "1880:1880"
