version: '2'
services:

  sth:
    image: telefonicaiot/fiware-sth-comet
    depends_on:
      - mongodb
    networks:
      subs:
        aliases:
          - sth
          - comet
          - history
    environment:
      STH_HOST: "0.0.0.0"
      DB_URI: "mongodb:27017"


  mongodb:
    image: "mongo:3.2"
    networks:
      subs:
        aliases:
          - mongodb

  mqtt:
    image: ansi/mosquitto
    ports:
      - "1883:1883"
    networks:
      subs:
        aliases:
          - mqtt

  iotagent:
    image: "iotmid-docker:5000/jenkins/iotagent-json:7f188b8"
    depends_on:
      - mongodb
      - mqtt
    volumes:
      - ./iotagent/config.js:/opt/iotajson/config.js:Z
    networks:
      subs:
        aliases:
          - iotagent
          - idas

  orion:
    image: fiware/orion
    depends_on:
      - mongodb
    command: -dbhost mongodb
    networks:
      subs:
        aliases:
          - orion

  # mysql:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: not_safe
  #   networks:
  #     subs:
  #       aliases:
  #         - mysql
  #
  # cygnus:
  #   image: fiware/cygnus-ngsi
  #   volumes:
  #     - ./cygnus/agent.conf:/opt/apache-flume/conf/agent.conf
  #   networks:
  #     subs:
  #       aliases:
  #         - cygnus

  device-manager:
    image: "iotmid-docker:5000/jenkins/devicemanager:efd5d37"
    depends_on:
      - mongodb
    networks:
      subs:
        aliases:
          - devm

  auth:
    image: "iotmid-docker:5000/jenkins/auth:24e66a7"
    depends_on:
      - mongodb
      - apigw
    networks:
      subs:
        aliases:
          - auth

  postgres:
    image: "postgres:9.4"
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
    networks:
      subs:
        aliases:
          - postgres

  apigw:
    image: "kong:0.10.0"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      # - "7946:7946"
      # - "7946:7946/udp"  # cluster
    environment:
      KONG_DATABASE: "postgres"
      KONG_CASSANDRA_CONTACT_POINTS: "postgres"
      KONG_PG_HOST: "postgres"
    networks:
      subs:
        aliases:
          - apigw
          - kong
          
  perseo-core:
    image: telefonicaiot/perseo-core
    command: -perseo_fe_url perseo-fe:9090
    networks:
      subs:

  perseo-fe:
    image: telefonicaiot/perseo-fe
    depends_on:
      - perseo-core
      - mongodb
    environment:
      - PERSEO_MONGO_HOST=mongodb
      - PERSEO_CORE_URL=http://perseo-core:8080
    networks:
      subs:

networks:
  subs:
