version: '2'
services:

  certs:
    image: nginx
    restart: always
    depends_on:
      - apigw
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/certs
      - ./certs/default.conf:/etc/nginx/conf.d/default.conf

  # sth:
  #   image: telefonicaiot/fiware-sth-comet
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   networks:
  #     default:
  #       aliases:
  #         - comet
  #         - history
  #   environment:
  #     STH_HOST: "0.0.0.0"
  #     DB_URI: "mongodb:27017"


  mongodb:
    image: "mongo:3.2"
    restart: always
    user: "mongodb"

  mqtt:
    image: powerbr/mosquitto:1.0
    restart: always
    ports:
      - "1883:1883"

  iotagent:
    image: powerbr/iotagent-json:1.0
    restart: always
    depends_on:
      - mongodb
      - mqtt
    networks:
      default:
        aliases:
          - idas

  # coap:
  #   image: powerbr/lightweightm2m-iotagent:
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - "127.0.0.1:4041:4041"
  #     - 5684:5684/udp

  gui:
    image: powerbr/gui:latest
    restart: always

  orion:
    image: powerbr/orion:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - "127.0.0.1:1026:1026"
    command: -dbhost mongodb

  device-manager:
    image: powerbr/device-manager:latest
    restart: always
    depends_on:
      - mongodb
    networks:
      default:
        aliases:
          - devm

  auth:
    image: dojot/auth:latest
    restart: always
    depends_on:
      - mongodb
      - apigw
    environment:
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PWD: ""
      KONG_URL: "http://apigw:8001"

  postgres:
    image: "ppc64le/postgres:9.4"
    restart: always
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
    networks:
      default:
        aliases:
          - kong-db

  apigw:
    image: powerbr/pep-kong:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "postgres"
    networks:
      default:
        aliases:
          - kong

  # pdp-ws:
  #   image: dojot/pdp-ws:0.2.0-nightly20171010
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "9763:9763"
  #   volumes:
  #     - ./pdpws/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:Z
  #
  # perseo-core:
  #   image: telefonicaiot/perseo-core
  #   restart: always
  #   command: -perseo_fe_url perseo-fe:9090
  #
  # perseo-fe:
  #   image: dojot/perseo-fe:0.2.0-nightly20171010
  #   restart: always
  #   ports:
  #     - "127.0.0.1:9090:9090"
  #   depends_on:
  #     - perseo-core
  #     - mongodb
  #   environment:
  #     - PERSEO_MONGO_HOST=mongodb
  #     - PERSEO_CORE_URL=http://perseo-core:8080
  #     - PERSEO_ORION_URL=http://orion:1026/NGSI10/updateContext
  #
  # mashup:
  #   image: dojot/mashup:0.2.0-nightly20171010
  #   restart: always
